version: "1"
services:
    app:
        build: .
        user: app
        container_name: php82
        working_dir: /home/app/src
        volumes:
            - ./:/home/app/src
        environment:
            - SAMPLE_ENV_VAR=xxx
        #tty: true
